### ISSUE TITLE
replacing previous import by 'scales::alpha

### ISSUE THREAD

**Issue by vnijs** [fawda123/NeuralNetTools#13]
I'm liking NeuralNetTools and import it to visualize output from a nnet model in a shiny-based package (see link below for an example).

http://vnijs.rady.ucsd.edu:3838/analytics/?url=model/ann/&SSUID=28e902038f

A (minor) issue is that I'm getting the warning below when loading (importing) the library. I think this might be due to the fact that ggplot2 2.0 already imports scales::alpa. Is there are fix you can suggest?

Thanks,

Vincent

> library(NeuralNetTools)
Warning message:
replacing previous import by ‘scales::alpha’ when loading ‘NeuralNetTools’

**Comment by fawda123** [comment]
Thanks for pointing that out, the latest commit should fix the problem a9258b846ac39d3daec0cbeba909b2b5b4b0e2bc

-Marcus

**Comment by fawda123** [comment]
And btw, I'd like to see the Shiny app you're created but it looks like I need authentication credentials.

**Comment by vnijs** [comment]
Seems to work. Thanks! You shouldn't need authentication. The link below should work fine.

http://vnijs.rady.ucsd.edu:3838/analytics/?url=model/ann/&SSUID=28e902038f

If not, you can install locally. Install instructions linked below:

http://vnijs.github.io/radiant/install.html
