### ISSUE TITLE
unable to modify size and legend of plotted neural net

### ISSUE THREAD

**Issue by ykl7** [fawda123/NeuralNetTools#16]

**Comment by fawda123** [comment]
You can create legends using the base function:
```r

librarynnet)

data(neuraldat) 
set.seed(123)

mod <- nnet(Y1 ~ X1 + X2 + X3, data = neuraldat, size = 5)
 
plotnet(mod)  
legend('topright', 
  c('node', 'weight'), 
  pch = c(16, NA), 
  lty = c(NA, 1), 
  col = c('lightblue', 'black')
  )
```
Can you please provide an example of the problem?

**Comment by ykl7** [comment]
Thanks @fawda123 it's working fine now. yesterday i was unable to use the plotnet function to get a graph when it wass followed by the olden function. That started working now too.
