### ISSUE TITLE
Error when plotting 

### ISSUE THREAD

**Issue by basaldella** [fawda123/NeuralNetTools#17]
Hello, 

I have a strange error when trying to use `plotnet`. Let's assume I have two models, called `m1` and `m2`, which are trained using the exact same formula on two different datasets.

If I do
```R
> plotnet(m1,alpha=0.6)
```

Everything works fine.

But if run 
```R
> plotnet(m2,alpha=0.6)
```
What i get is

```R
Error in as.character(forms) : 
  cannot coerce type 'closure' to vector of type 'character'
```

Do you have any idea of what could cause this problem?

**Comment by fawda123** [comment]
Can you explain the models and input data a bit more?  I can't diagnose anything from the example.

**Comment by basaldella** [comment]
Yeah, I'm sorry, you're right. I created a [gist](https://gist.github.com/basaldella/ebb672efbb12c565dec585a6ed0916b4) with the example code and data, I hope this helps.

**Comment by fawda123** [comment]
You need to rename the `formula` object to something else.  `formula` is already a function in R and that's causing problems in the NeuralNetTools functions.  This should work:  
```{r}
library(nnet)
library(NeuralNetTools)

formulaA = AKEC ~ 
  tf +
  Freq_Sentence + 
  Height + 
  LifeSpan + 
  Depth +
  tf.idf + 
  Maximality

formulaS = SEMEVAL2010 ~ 
  tf +
  Freq_Sentence + 
  Height + 
  LifeSpan + 
  Depth +
  tf.idf + 
  Maximality

AKEC_train <- read.csv("https://gist.githubusercontent.com/basaldella/ebb672efbb12c565dec585a6ed0916b4/raw/b9dc49dffa6e8caa758cacd0a5acf8148b73c89e/akec.top.csv",stringsAsFactors = TRUE)
SEMEVAL_train <- read.csv("https://gist.githubusercontent.com/basaldella/ebb672efbb12c565dec585a6ed0916b4/raw/b9dc49dffa6e8caa758cacd0a5acf8148b73c89e/semeval.top.csv",stringsAsFactors = TRUE)

set.seed(1203) 
akecModel = nnet(formulaA,
                 size = length(attr(terms(formulaA),"variables")) * 2,
                 entropy=T,data = AKEC_train)


set.seed(1203) 
semevalModel = nnet(formulaS,
                    size = length(attr(terms(formulaS),"variables")) * 2,
                    entropy=T,data = SEMEVAL_train)

plotnet(akecModel)
plotnet(semevalModel)

```

**Comment by basaldella** [comment]
Now it works like a charm. Sorry for my mistake, but I'm far from being an R expert... Thanks a lot for your help!

**Comment by fawda123** [comment]
No problem, I'm happy to help.
