### ISSUE TITLE
olden.default fails if output variable has some special characters

### ISSUE THREAD

**Issue by taunometsalu** [fawda123/NeuralNetTools#19]
With some characters in the out_var (e.g. if the levels are calculated using `cut()`), the following line fails:

`out_ind <- grep(out_var, y_names)`

It could be changed to fixed grep:

`out_ind <- grep(out_var, y_names, fixed = TRUE)`

**Comment by fawda123** [comment]
Fixed on dev branch: d44092563ca32e1984eec38cc890f31d12dbc783
