### ISSUE TITLE
Question: olden with Keras model

### ISSUE THREAD

**Issue by nba2020** [fawda123/NeuralNetTools#21]
Is the olden() function able to take as `mod_in` input a NN model that was produced from the Keras package in R?

**Comment by fawda123** [comment]
No, the functions in this package only work for objects from the [nnet](https://cran.r-project.org/package=nnet), [neuralnet](https://cran.r-project.org/package=neuralnet), [RSNNS](https://cran.r-project.org/package=RSNNS), and [caret](https://cran.r-project.org/package=caret) packages.  However, there is a numeric method where you can manually input the weights to get the results: 
```r
# B1-H1, I1-H1, I2-H1, B1-H2, I1-H2, I2-H2, B2-O1, H1-O1, H2-O1.
wts_in <- c(13.12, 1.49, 0.16, -0.11, -0.19, -0.16, 0.56, -0.52, 0.81)
struct <- c(2, 2, 1) #two inputs, two hidden, one output 

olden(wts_in, struct)
```

**Comment by nba2020** [comment]
OK, thank for clarifying @fawda123 :)
