### ISSUE TITLE
Plotting pruned networks

### ISSUE THREAD

**Issue by mngreene** [fawda123/NeuralNetTools#4]
Hi Marcus,

Thank you very much for developing a package to visualise NNs.  

I noticed it does not allow to visualise pruned networks however. 
Recently I approached the developer of RSNNS to extend the capacity of the package to introduce pruning capacity - a very useful feature indeed which is now available as standard in RSNNS. 
Would it be possible please to look into extending the functionality of NeuralNetTools to allow plotting pruned networks as well? 

Thank you very much in advance. 

Regards,

Max

**Comment by fawda123** [comment]
Max, try the v1.3.3 release.  I tested plotnet with a simple pruned network and it worked as expected.  The other functions should work though I'm getting screwy results with lekprofile.

-Marcus
