### ISSUE TITLE
garson-method nnet with one hidden-unit

### ISSUE THREAD

**Issue by AndreasFischer** [fawda123/NeuralNetTools#8]
#There seems to be a problem with your garson-method in case of nnets with one hidden-unit:

set.seed(0);garson(nnet(data.frame(rnorm(100),rnorm(100)),rnorm(100),size=2)) #works
set.seed(0);garson(nnet(data.frame(rnorm(100),rnorm(100)),rnorm(100),size=1)) #does not work

**Comment by fawda123** [comment]
see latest release/push
